[2022-11-12T11:47:10.515+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: load_to_dwh_v2.load_raw_data manual__2022-11-12T11:43:30.200309+00:00 [queued]>
[2022-11-12T11:47:10.528+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: load_to_dwh_v2.load_raw_data manual__2022-11-12T11:43:30.200309+00:00 [queued]>
[2022-11-12T11:47:10.528+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-12T11:47:10.529+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 6
[2022-11-12T11:47:10.529+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-12T11:47:10.549+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): load_raw_data> on 2022-11-12 11:43:30.200309+00:00
[2022-11-12T11:47:10.554+0000] {standard_task_runner.py:54} INFO - Started process 196 to run task
[2022-11-12T11:47:10.558+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'load_to_dwh_v2', 'load_raw_data', 'manual__2022-11-12T11:43:30.200309+00:00', '--job-id', '206', '--raw', '--subdir', 'DAGS_FOLDER/postgre_create_table.py', '--cfg-path', '/tmp/tmp_nu6gyp5']
[2022-11-12T11:47:10.559+0000] {standard_task_runner.py:83} INFO - Job 206: Subtask load_raw_data
[2022-11-12T11:47:10.560+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/postgre_create_table.py
[2022-11-12T11:47:10.930+0000] {task_command.py:384} INFO - Running <TaskInstance: load_to_dwh_v2.load_raw_data manual__2022-11-12T11:43:30.200309+00:00 [running]> on host f73c12cbae8a
[2022-11-12T11:47:11.033+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=nahom
AIRFLOW_CTX_DAG_ID=load_to_dwh_v2
AIRFLOW_CTX_TASK_ID=load_raw_data
AIRFLOW_CTX_EXECUTION_DATE=2022-11-12T11:43:30.200309+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-12T11:43:30.200309+00:00
[2022-11-12T11:47:11.034+0000] {logging_mixin.py:117} INFO - writing data..............
[2022-11-12T11:47:11.035+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgre_create_table.py", line 20, in load_raw_data
    df = pd.read_csv(path, sep=",", index_col=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/cleanned_data.csv'
[2022-11-12T11:47:11.048+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=load_to_dwh_v2, task_id=load_raw_data, execution_date=20221112T114330, start_date=20221112T114710, end_date=20221112T114711
[2022-11-12T11:47:11.065+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 206 for task load_raw_data ([Errno 2] No such file or directory: '/opt/airflow/data/cleanned_data.csv'; 196)
[2022-11-12T11:47:11.090+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-12T11:47:11.123+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
