[2022-11-12T11:21:16.360+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: load_to_dwh_v2.extract_and_clean_data manual__2022-11-12T11:21:14.929505+00:00 [queued]>
[2022-11-12T11:21:16.375+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: load_to_dwh_v2.extract_and_clean_data manual__2022-11-12T11:21:14.929505+00:00 [queued]>
[2022-11-12T11:21:16.376+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-12T11:21:16.376+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 6
[2022-11-12T11:21:16.376+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-12T11:21:16.399+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): extract_and_clean_data> on 2022-11-12 11:21:14.929505+00:00
[2022-11-12T11:21:16.405+0000] {standard_task_runner.py:54} INFO - Started process 92 to run task
[2022-11-12T11:21:16.409+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'load_to_dwh_v2', 'extract_and_clean_data', 'manual__2022-11-12T11:21:14.929505+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/postgre_create_table.py', '--cfg-path', '/tmp/tmpgluaemxz']
[2022-11-12T11:21:16.409+0000] {standard_task_runner.py:83} INFO - Job 112: Subtask extract_and_clean_data
[2022-11-12T11:21:16.411+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/postgre_create_table.py
[2022-11-12T11:21:16.879+0000] {task_command.py:384} INFO - Running <TaskInstance: load_to_dwh_v2.extract_and_clean_data manual__2022-11-12T11:21:14.929505+00:00 [running]> on host 7ed92ead7851
[2022-11-12T11:21:17.002+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=nahom
AIRFLOW_CTX_DAG_ID=load_to_dwh_v2
AIRFLOW_CTX_TASK_ID=extract_and_clean_data
AIRFLOW_CTX_EXECUTION_DATE=2022-11-12T11:21:14.929505+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-12T11:21:14.929505+00:00
[2022-11-12T11:21:17.004+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/pandas/util/_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)

[2022-11-12T11:21:44.778+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py:586: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  return _read(filepath_or_buffer, kwds)

[2022-11-12T11:21:48.836+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgre_create_table.py", line 28, in clean_df
    df.to_csv('/opt/airflow/data/cleanned_data.csv',index=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/cleanned_data.csv'
[2022-11-12T11:21:48.892+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=load_to_dwh_v2, task_id=extract_and_clean_data, execution_date=20221112T112114, start_date=20221112T112116, end_date=20221112T112148
[2022-11-12T11:21:48.946+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 112 for task extract_and_clean_data ([Errno 13] Permission denied: '/opt/airflow/data/cleanned_data.csv'; 92)
[2022-11-12T11:21:49.034+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-12T11:21:49.120+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
